version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: studysmartbuddy-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    # No authentication for development
    command: mongod --bind_ip_all
    restart: unless-stopped

volumes:
  mongodb_data: