version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: studysmartbuddy-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    # No authentication for development
    command: mongod --bind_ip_all
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: studysmartbuddy-client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://server:5000/api
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: studysmartbuddy-server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/studysmartbuddy
      - NODE_ENV=development
      - AI_PROVIDER=${AI_PROVIDER:-openrouter}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/exports:/app/exports
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data: